# Generated by Django 4.2.1 on 2023-05-23 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_reservation", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Aeroport",
            fields=[
                (
                    "code",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("nom", models.CharField(max_length=255)),
                ("ville", models.CharField(max_length=255)),
                ("code_ville", models.CharField(max_length=255)),
                ("pays", models.CharField(max_length=255)),
                ("code_pays", models.CharField(max_length=255)),
            ],
        ),
    ]
