# Generated by Django 4.2.1 on 2023-05-23 23:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app_reservation", "0002_aeroport"),
    ]

    operations = [
        migrations.CreateModel(
            name="Vol",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_depart", models.DateTimeField()),
                ("date_arrivee", models.DateTimeField()),
                ("prix", models.DecimalField(decimal_places=2, max_digits=10)),
                ("nombre_place", models.IntegerField()),
                (
                    "aeroport_arrivee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vols_arrivee",
                        to="app_reservation.aeroport",
                    ),
                ),
                (
                    "aeroport_depart",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vols_depart",
                        to="app_reservation.aeroport",
                    ),
                ),
                (
                    "compagnie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="compagnie",
                        to="app_reservation.compagnie",
                    ),
                ),
            ],
        ),
    ]
