# Generated by Django 4.2.1 on 2023-05-24 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app_reservation", "0004_hotel"),
    ]

    operations = [
        migrations.CreateModel(
            name="Chambre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type_chambre", models.CharField(max_length=255)),
                ("description", models.CharField(max_length=255)),
                ("prix", models.DecimalField(decimal_places=2, max_digits=10)),
                ("nombre_place", models.DecimalField(decimal_places=2, max_digits=10)),
                ("photo", models.CharField(max_length=255)),
                (
                    "hotel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hotel",
                        to="app_reservation.hotel",
                    ),
                ),
            ],
        ),
    ]
