# Generated by Django 4.2.1 on 2023-05-24 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_reservation", "0005_chambre"),
    ]

    operations = [
        migrations.CreateModel(
            name="Utilisateur",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=255)),
                ("prenom", models.CharField(max_length=255)),
                ("adresse", models.CharField(max_length=255)),
                ("email", models.CharField(max_length=255)),
                ("telephone", models.CharField(max_length=20)),
            ],
        ),
        
    ]
