# Generated by Django 4.2.1 on 2023-05-24 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_reservation", "0006_utilisateur"),
    ]

    operations = [
        migrations.AddField(
            model_name="utilisateur",
            name="mot_de_passe",
            field=models.CharField(default="passer", max_length=50),
            preserve_default=False,
        ),
    ]
