# Generated by Django 4.2.1 on 2023-05-24 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_reservation", "0007_utilisateur_mot_de_passe"),
    ]

    operations = [
        migrations.CreateModel(
            name="Voiture",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("marque", models.CharField(max_length=255)),
                ("modele", models.CharField(max_length=255)),
                ("localisation", models.CharField(max_length=255)),
                ("annee", models.IntegerField()),
                ("type", models.CharField(max_length=255)),
                ("prix", models.DecimalField(decimal_places=2, max_digits=10)),
                ("nombre_place", models.IntegerField()),
                ("photo", models.CharField(max_length=255)),
                ("disponible", models.BooleanField(default=True)),
            ],
        ),
    ]
