# Generated by Django 4.2.1 on 2023-05-24 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app_reservation", "0010_reservations_hotel"),
    ]

    operations = [
        migrations.CreateModel(
            name="Location_Voiture",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_reservation", models.DateTimeField()),
                ("date_restitution", models.DateTimeField()),
                (
                    "utilisateur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="utilisateur3",
                        to="app_reservation.utilisateur",
                    ),
                ),
                (
                    "voiture",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="voiture",
                        to="app_reservation.voiture",
                    ),
                ),
            ],
        ),
    ]
