# Generated by Django 4.2.1 on 2023-05-29 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_reservation", "0011_location_voiture"),
    ]

    operations = [
        migrations.AddField(
            model_name="hotel",
            name="ville",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
    ]
