# Generated by Django 4.2.1 on 2023-05-29 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_reservation", "0013_alter_chambre_nombre_place_alter_chambre_prix"),
    ]

    operations = [
        migrations.AddField(
            model_name="hotel",
            name="photo",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
    ]
