# Generated by Django 4.2.1 on 2023-06-12 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_reservation", "0014_hotel_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="location_voiture",
            name="disponible",
            field=models.BooleanField(default=False),
        ),
    ]
