# Generated by Django 4.2.1 on 2023-06-19 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_reservation", "0016_remove_location_voiture_disponible_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="vol",
            name="image",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
